// front_end_for_TMS/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  email = '';
  password = '';

  handleSubmit(): void {
    console.log({ email: this.email, password: this.password });
  }
}

<div class="login-container">
  <div class="login-card">
    <h2 class="login-title">Welcome back</h2>
    <p class="login-subtitle">Enter your credentials to access your account.</p>

    <form (ngSubmit)="handleSubmit()" #loginForm="ngForm">
      <div class="form-group">
        <label for="email" class="form-label">Email Address</label>
        <input
          id="email"
          name="email"
          type="email"
          class="form-input"
          placeholder="name@company.com"
          [(ngModel)]="email"
          required
        />
      </div>

      <div class="password-field">
        <div class="password-label-container">
          <label for="password" class="form-label">Password</label>
          <a routerLink="/reset-password" class="forgot-link">Forgot?</a>
        </div>
        <input
          id="password"
          name="password"
          type="password"
          class="form-input"
          placeholder="••••••••"
          [(ngModel)]="password"
          required
        />
      </div>

      <button type="submit" class="btn btn-primary">Sign In</button>
    </form>
  </div>
</div>

// front_end_for_TMS/src/pages/Login.tsx
import React from "react";
import { Link as RouterLink } from "react-router-dom";
import {
  Box,
  Button,
  TextField,
  Typography,
  Link,
  Paper,
  Stack,
} from "@mui/material";

const Login = () => {
  const handleSubmit = (e: React.BaseSyntheticEvent): void => {
    e.preventDefault();
    const data = new FormData(e.currentTarget);
    console.log(Object.fromEntries(data.entries()));
  };

  return (
    <Box sx={{ display: "flex", justifyContent: "center", mt: 8, px: 2 }}>
      <Box sx={{ width: 400 }}>
        <Paper
          elevation={3}
          sx={{ p: 4, borderRadius: 2, width: "100%", boxSizing: "border-box" }}
        >
          <Typography variant="h5" sx={{ fontWeight: 700, mb: 1 }}>
            Welcome back
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
            Enter your credentials to access your account.
          </Typography>

          <Box component="form" onSubmit={handleSubmit} noValidate>
            <Stack spacing={2.5}>
              <Box>
                <Typography
                  variant="subtitle2"
                  sx={{ mb: 0.5, fontWeight: 700 }}
                >
                  Email Address
                </Typography>
                <TextField
                  fullWidth
                  name="email"
                  type="email"
                  placeholder="name@company.com"
                  required
                  size="small"
                />
              </Box>

              <Box>
                <Box
                  sx={{
                    display: "flex",
                    justifyContent: "space-between",
                    mb: 0.5,
                  }}
                >
                  <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                    Password
                  </Typography>
                  <Link
                    component={RouterLink}
                    to="/reset-password"
                    underline="none"
                    sx={{ fontSize: "0.875rem", fontWeight: 600 }}
                  >
                    Forgot?
                  </Link>
                </Box>
                <TextField
                  fullWidth
                  name="password"
                  type="password"
                  placeholder="••••••••"
                  required
                  size="small"
                />
              </Box>

              <Button
                fullWidth
                type="submit"
                variant="contained"
                size="large"
                sx={{ textTransform: "none", fontWeight: 700, py: 1.5 }}
              >
                Sign In
              </Button>
            </Stack>
          </Box>
        </Paper>
      </Box>
    </Box>
  );
};

export default Login;
